### ISSUE TITLE
Missing MLTED, RF and TreeVec panels for example inputs

### ISSUE THREAD

**Issue by Ignatiocalvin** [SayakaMiura/ClonePhyTester#3]
Hello.
I've tested both All_SequenceList and Test_SequenceList as inputs and the only existing panels in the .jpg files were the mutation orders. Was there something I might have missed?

Thanks.

**Comment by SayakaMiura** [comment]
Is it possible for you to share your command line you used together with modifications you made in the input data or the code (if any). I can look into the issue.

**Comment by Ignatiocalvin** [comment]
From the ClonePhyTester directory: 
`$ python clonephytester.py Example/Test.input`

Test.input (Ran two times for Test_SequenceList.txt and All_SequenceList.txt):

Data	Example/Test_SequenceList.txt
R	Rscript
MLTED	./main

I haven't made any modificiations whatsoever to the code or files. I have tried using inferred sequences from other tools but the metrics were still missing. Below is the Test_summary.jpg

Thanks 

![image](https://user-images.githubusercontent.com/50834160/129369735-a18e72e3-bc1e-4317-a08a-8b00c9f1a1dd.png)

**Comment by SayakaMiura** [comment]
I think Rscript  (R. you may need to set up the path), ./main (from MLTED-master.zip), and/or java (for phyloNet_3.6.1.jar) are not installed properly. Please confirm you can call them from the terminal by simply typing:
$ Rscript
$ ./main 
$ java -jar PhyloNet_3.6.1.jar

**Comment by Ignatiocalvin** [comment]
Hi, this is what was shown: 
![image](https://user-images.githubusercontent.com/50834160/129385420-4481021e-3f96-4990-a123-170b2fb05031.png)
![image](https://user-images.githubusercontent.com/50834160/129385755-7ec9b8ec-6689-4cb5-96ed-061cf155634a.png)
![image](https://user-images.githubusercontent.com/50834160/129385777-07a01228-2e93-427f-a3c9-f89e833bdaee.png)

Additionally, I also tried changing Test.input:

Data	Example/Test_SequenceList.txt
R	/home/hidayaic/miniconda3/envs/clonePhyTester/bin/Rscript
MLTED	/data/analysis/pedion/A09R/user_folders/hidayaic/ClonePhyTester/main

I also tried to use the main in the MLTED-master directory but to no avail.

**Comment by SayakaMiura** [comment]
For the Test.input, please change the line for MLTED into, 
MLTED ./main
It should produce all the results.

**Comment by Ignatiocalvin** [comment]
Sorry, that still didn't work. :(

**Comment by SayakaMiura** [comment]
Then, maybe, clone phylogenies are not infred. Did you install MEGA (https://www.megasoftware.net/) and can you call megacc? Please confirm the following command:
$ megacc

**Comment by Ignatiocalvin** [comment]
Yup, I had megacc installed from the start. Here's the output:
![image](https://user-images.githubusercontent.com/50834160/129404027-50ff483e-08c9-48e1-84ed-aa96580b30e3.png)

**Comment by SayakaMiura** [comment]
When you ran clonephytester.py, did you see some error message or warning message on the terminal? I think the issue is the phylogeny inference, but I do not know when it failed.

**Comment by Ignatiocalvin** [comment]
These are the errors I encountered when testing All_SequenceList.txt. There were no errors regarding inferred sequence not found when testing for Test_SequenceList.txt so I don't think the second error is a problem. 

In the resulting summary.xlsx file, the column 'YourMethod' has only NA values in the sheets MLTED, RF, and TreeVec whereas the sheets for the mutation orders were not so.

I tried debugging manually and it seems that the Compute_RF() and Compute_MLTED() in Functions.py did not return any results.

![image](https://user-images.githubusercontent.com/50834160/129407516-45cbb836-ca0c-451b-9db3-4e86efb7bd55.png)

![image](https://user-images.githubusercontent.com/50834160/129407665-9cda6b86-c35e-4df3-b1af-dd7f0259c243.png)

**Comment by SayakaMiura** [comment]
The issue is an inferred phylogeny does not have branch lengths. This is a bug in megacc. I contacted the developer to fix it. I will let you know once he fixes the issue.

**Comment by Ignatiocalvin** [comment]
Appreciate it. Many thanks.

**Comment by SayakaMiura** [comment]
The latest version of MEGA does not support branch length calculation for MP. So, please download MEGA-CC from,
Windows: https://www.megasoftware.net/releases/MEGA_X_CC_10.1.7_win64_setup.exe
Ubuntu/Debian: https://www.megasoftware.net/releases/megax-cc_10.1.7-1_amd64.deb 
Redhat/Fedora: https://www.megasoftware.net/releases/megax-cc-10.1.7-1.x86_64.rpm
macOS: https://www.megasoftware.net/releases/MEGAX_CC_10.1.7_installer.pkg
If you still do not get the results, please let me know.
